name: Update WakaTime stats
 permissions:
  contents: write
  id-token: write
  pull-requests: write
  actions: read

on:
  schedule:
    - cron: '0 * * * *' # roda a cada hora
  workflow_dispatch:     # permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update WakaTime stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # usa o segredo que você criou

