name: Waka Readme Stats Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # roda todo dia à meia-noite (UTC)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Waka Readme Stats
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # Se você usa WakaTime
          SECTION_NAME: "waka-readme-stats"
          SHOW_OS: "true"
          SHOW_PROJECTS: "true"
          SHOW_EDITORS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_COMMIT: "true"
          SHOW_LANGUAGE: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_LOC_CHART: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_PROFILE_VIEWS: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_UPDATED_DATE: "true"
          SHOW_TOTAL_CODE_TIME: "true"
          COMMIT_BY_ME: "true"
          COMMIT_MESSAGE: "Update Waka Readme Stats"
          COMMIT_USERNAME: "your-github-username"
          COMMIT_EMAIL: "your-email@example.com"
          LOCALE: "en"
          UPDATED_DATE_FORMAT: "MMM Do, YYYY"



